# Generated by Django 4.2.2 on 2023-06-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imagecontentblock_country_imagecontentblock_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontentblock',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='videocontentblock',
            name='region',
            field=models.CharField(default='', max_length=200),
        ),
    ]
