# Generated by Django 4.1.7 on 2023-07-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_uploadedimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('script', models.TextField(help_text='Embed your scripts, HTML code, or iframes here.')),
                ('post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='videocontentblock',
            name='post',
        ),
        migrations.DeleteModel(
            name='ImageContentBlock',
        ),
        migrations.DeleteModel(
            name='VideoContentBlock',
        ),
    ]
